### ISSUE TITLE
webcomponents.org links broken

### ISSUE THREAD

**Issue by Malvoz** [EPA-WG/embed-page#13]
Links to webcomponents.org in the readme.md file and also in the repo description are broken.

E.g.
<s>https://www.webcomponents.org/element/EPA-WG/embed-page</s>
https://www.webcomponents.org/element/embed-page

**Comment by sashafirsov** [comment]
@Malvoz , thanks for pointing. Links are fixed.

**Comment by Malvoz** [comment]
@sashafirsov 

This link too: https://www.webcomponents.org/element/EPA-WG/embed-page/demo/demo/index.html in [README.md#L69](https://github.com/EPA-WG/embed-page/blame/master/README.md#L69)

**Comment by sashafirsov** [comment]
@Malvoz , thanks the line has been removed in sources. Will be replaced on webcomponents.org in next release along with external microapplication sample.
